# Generated by Django 2.0.10 on 2019-02-21 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190217_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follwering',
            field=models.ManyToManyField(related_name='_user_follwering_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(related_name='_user_follwers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
