# Generated by Django 2.0.10 on 2019-02-21 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190221_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follwering',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follwers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
